version: '3'
services:
  backend:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      DB_HOST: "localhost"
      DB_USER: "root"
      DB_PASSWORD: "test@123"
      DB_NAME: "expense_tracker"
